import prettier from 'eslint-config-prettier';
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

export default defineConfig(
	// Generated by `svelte-kit sync` — not source, and rewritten on every build.
	globalIgnores(['.svelte-kit/**', 'build/**']),
	js.configs.recommended,
	ts.configs.recommended,
	prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef
			// lint rule on TypeScript projects.
			'no-undef': 'off'
		}
	}
);
