/**
 * The whole server schema, hand-authored. One file, one truth.
 *
 * ── How the Better Auth half of this file was produced ───────────────────────
 * NOT from memory. `@better-auth/drizzle-adapter` ships its own generator; its
 * `generateDrizzleSchema()` was run against this exact plugin set
 * (`passkey({})`, `twoFactor({ allowPasswordless: true })`, `bearer()`) with
 * `provider: 'pg'`, and its output is reproduced verbatim below. The adapter
 * resolves `config.schema[model]` and then `table[camelCaseFieldName]`, so a
 * single transposed character is a runtime error, not a type error. If a plugin
 * is added or changed here, regenerate — do not retype.
 *
 * ── `rev` is ONE sequence across both entity tables ──────────────────────────
 * This is the load-bearing decision in the file.
 *
 * `list` and `task` both draw `rev` from `ikoroRevSeq`, a single `bigserial`.
 * Two independent sequences would be WRONG: a client that pulled up to `rev=100`
 * from `list` would skip every `task` row numbered 40–99 forever, because the
 * client cursor is a single number compared against both tables. One sequence
 * makes `rev` globally ordered, which is what `GET /changes` assumes.
 *
 * A Postgres sequence hands out each value exactly once — under concurrency, by
 * design, and never rolls back on abort. That is what makes it safe here and is
 * why `max(rev) + 1` or `count(*) + 1` must never be used instead: both read
 * state and write state, so two concurrent inserts get the same number and one
 * row silently disappears from the feed forever.
 *
 * Gaps are expected and harmless. A sequence can burn a value when a transaction
 * that took one rolls back, so `rev` is monotonic and unique, never contiguous.
 * The client must treat `nextRev` as "everything at or below this has been
 * seen", which is exactly what `rev > since` gives.
 */

import { relations } from 'drizzle-orm';
import {
	boolean,
	bigint,
	index,
	integer,
	jsonb,
	pgTable,
	text,
	timestamp
} from 'drizzle-orm/pg-core';

// ── the shared revision sequence ──────────────────────────────────────────────

/**
 * The name of the ONE sequence `list.rev` and `task.rev` both draw from.
 *
 * It is a plain string rather than a `pgSequence()` object because a column
 * default takes `{ name: string }`: `generatedByDefaultAsIdentity({ name })`.
 * Both tables pass this same constant, and drizzle-kit emits
 * `GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME ikoro_rev_seq)` for each —
 * Postgres creates the sequence on the first reference and the second table
 * reuses it.
 *
 * The name is referenced in three places (both columns, and the explicit
 * `nextval()` on the update path in `queries.ts`). Keeping it here means
 * renaming the sequence is a one-line change rather than a hunt.
 */
export const REV_SEQUENCE_NAME = 'ikoro_rev_seq';

// ── Better Auth tables (generated; do not retype) ────────────────────────────

export const user = pgTable('user', {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	emailVerified: boolean('email_verified').default(false).notNull(),
	image: text('image'),
	createdAt: timestamp('created_at').notNull(),
	updatedAt: timestamp('updated_at')
		.$onUpdate(() => new Date())
		.notNull(),
	twoFactorEnabled: boolean('two_factor_enabled').default(false)
});

export const session = pgTable(
	'session',
	{
		id: text('id').primaryKey(),
		expiresAt: timestamp('expires_at').notNull(),
		token: text('token').notNull().unique(),
		createdAt: timestamp('created_at').notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => new Date())
			.notNull(),
		ipAddress: text('ip_address'),
		userAgent: text('user_agent'),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' })
	},
	(t) => [index('session_userId_idx').on(t.userId)]
);

export const account = pgTable(
	'account',
	{
		id: text('id').primaryKey(),
		accountId: text('account_id').notNull(),
		providerId: text('provider_id').notNull(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		accessToken: text('access_token'),
		refreshToken: text('refresh_token'),
		idToken: text('id_token'),
		accessTokenExpiresAt: timestamp('access_token_expires_at'),
		refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
		scope: text('scope'),
		password: text('password'),
		createdAt: timestamp('created_at').notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => new Date())
			.notNull()
	},
	(t) => [index('account_userId_idx').on(t.userId)]
);

export const verification = pgTable(
	'verification',
	{
		id: text('id').primaryKey(),
		identifier: text('identifier').notNull(),
		value: text('value').notNull(),
		expiresAt: timestamp('expires_at').notNull(),
		createdAt: timestamp('created_at').notNull(),
		updatedAt: timestamp('updated_at')
			.$onUpdate(() => new Date())
			.notNull()
	},
	(t) => [index('verification_identifier_idx').on(t.identifier)]
);

export const passkey = pgTable(
	'passkey',
	{
		id: text('id').primaryKey(),
		name: text('name'),
		publicKey: text('public_key').notNull(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		credentialID: text('credential_id').notNull(),
		counter: integer('counter').notNull(),
		deviceType: text('device_type').notNull(),
		backedUp: boolean('backed_up').notNull(),
		transports: text('transports'),
		createdAt: timestamp('created_at'),
		aaguid: text('aaguid')
	},
	(t) => [
		index('passkey_userId_idx').on(t.userId),
		index('passkey_credentialID_idx').on(t.credentialID)
	]
);

export const twoFactor = pgTable(
	'two_factor',
	{
		id: text('id').primaryKey(),
		secret: text('secret').notNull(),
		backupCodes: text('backup_codes').notNull(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		verified: boolean('verified').default(true),
		failedVerificationCount: integer('failed_verification_count').default(0),
		lockedUntil: timestamp('locked_until')
	},
	(t) => [index('twoFactor_secret_idx').on(t.secret), index('twoFactor_userId_idx').on(t.userId)]
);

// ── sync: the idempotency ledger ─────────────────────────────────────────────
//
// ── A note on `withTimezone`, and why it is only on THESE tables ──────────────
// Every timestamp column from `list`, `task` and `applied_op` is
// `timestamptz`, not `timestamp`. It is not a preference: `updatedAt` is the
// input to last-writer-wins, so if a stored instant is shifted by the database's
// session timezone, every comparison is made against a slightly wrong value and
// two devices can permanently disagree about who won.
//
// Postgres silently converts `::timestamptz` into a zone-less `timestamp` using
// the SESSION timezone, and reads it back the same way. On a database left at
// UTC that round-trips exactly; the moment it is not — a restore, a `SET TIME
// ZONE`, a different provider default — the stored instant moves with no error
// anywhere. `timestamptz` stores the instant itself, so the round trip is exact
// regardless of configuration.
//
// The Better Auth columns above are left as their generator emitted them. This
// server does not own those reads and writes, they gate sign-in, and changing
// them cannot be verified without a live database. That asymmetry is deliberate
// and is the reason to revisit them only with a real Neon URL in hand.

/**
 * Every op id this server has ever committed, and the `rev` it was given.
 *
 * The primary key on `id` IS the idempotency guarantee. `ON CONFLICT (id) DO
 * NOTHING` makes the claim a single atomic statement: two concurrent retries of
 * the same op race on the unique index, exactly one wins, and the loser learns it
 * was a replay. There is no read-then-write window to lose.
 *
 * `userId` is stored so a replay can be rejected as `forbidden` rather than
 * silently reporting another account's revision back to the caller.
 *
 * `rev` is nullable only because an op is claimed *before* its row is written
 * and both happen in one statement (see `queries.ts`); a committed row always
 * has one.
 */
export const appliedOp = pgTable(
	'applied_op',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		kind: text('kind').notNull(),
		entityId: text('entity_id').notNull(),
		rev: bigint('rev', { mode: 'number' }),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull()
	},
	(t) => [
		index('applied_op_userId_idx').on(t.userId),
		index('applied_op_createdAt_idx').on(t.createdAt)
	]
);

// ── sync: the change feed ────────────────────────────────────────────────────

/**
 * A task list, as the server stores it.
 *
 * `id` is a CLIENT-GENERATED uuid (`crypto.randomUUID()` on the device), not a
 * server sequence. Two devices that create the same record offline must agree on
 * its identity without talking to each other first, so the client has to be the
 * one naming it.
 *
 * The payload is `jsonb`, not a column per field, for one specific reason:
 * `packages/sync` validates it with a Valibot schema and `mergeRow` compares it
 * by value. Spreading it into columns would mean the server's shape and the
 * wire's shape can drift, and `apps/app` would need a server round-trip for every
 * field it adds. The tradeoff is that Postgres cannot index inside the payload —
 * which nothing here needs, because the only queries are "everything for this
 * user above this rev".
 */
export const list = pgTable(
	'list',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		payload: jsonb('payload').notNull(),
		/** The client LWW clock. An INPUT to the merge, never the authority. */
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
		/** Server-assigned, globally monotonic. The pull cursor. */
		rev: bigint('rev', { mode: 'number' }).generatedByDefaultAsIdentity({
			name: REV_SEQUENCE_NAME
		}),
		/** Non-null means deleted. Deletes are ALWAYS soft. */
		deletedAt: timestamp('deleted_at', { withTimezone: true })
	},
	(t) => [index('list_userId_rev_idx').on(t.userId, t.rev)]
);

/** A task. Same contract as `list` — see the note there. */
export const task = pgTable(
	'task',
	{
		id: text('id').primaryKey(),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		payload: jsonb('payload').notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
		rev: bigint('rev', { mode: 'number' }).generatedByDefaultAsIdentity({
			name: REV_SEQUENCE_NAME
		}),
		deletedAt: timestamp('deleted_at', { withTimezone: true })
	},
	(t) => [index('task_userId_rev_idx').on(t.userId, t.rev)]
);

/**
 * Which table owns which entity kind.
 *
 * `EntityKind` is imported from `@ikoro/sync` — the wire protocol is the
 * authority on what kinds exist, and duplicating the list here is how a kind
 * ends up accepted by the client and rejected by the server.
 */
export const ENTITY_TABLES = { list, task } as const satisfies Record<string, unknown>;

// ── Relations v1 ─────────────────────────────────────────────────────────────

/**
 * Relations v1, deliberately — NOT `relations-v2`.
 *
 * The adapter degrades gracefully without them (`buildRelationKeysByModel`
 * returns an empty map and falls back to the model name), and v1 is enough for
 * everything this server does. `@better-auth/drizzle-adapter/relations-v2` is
 * the right call only if the schema moves to Relations v2, and switching is not
 * free. See VERSIONS.md §2.4.
 */
export const userRelations = relations(user, ({ many }) => ({
	sessions: many(session),
	accounts: many(account),
	passkeys: many(passkey),
	twoFactors: many(twoFactor),
	lists: many(list),
	tasks: many(task),
	appliedOps: many(appliedOp)
}));

export const sessionRelations = relations(session, ({ one }) => ({
	user: one(user, { fields: [session.userId], references: [user.id] })
}));

export const accountRelations = relations(account, ({ one }) => ({
	user: one(user, { fields: [account.userId], references: [user.id] })
}));

export const passkeyRelations = relations(passkey, ({ one }) => ({
	user: one(user, { fields: [passkey.userId], references: [user.id] })
}));

export const twoFactorRelations = relations(twoFactor, ({ one }) => ({
	user: one(user, { fields: [twoFactor.userId], references: [user.id] })
}));

export const listRelations = relations(list, ({ one }) => ({
	user: one(user, { fields: [list.userId], references: [user.id] })
}));

export const taskRelations = relations(task, ({ one }) => ({
	user: one(user, { fields: [task.userId], references: [user.id] })
}));

export const appliedOpRelations = relations(appliedOp, ({ one }) => ({
	user: one(user, { fields: [appliedOp.userId], references: [user.id] })
}));

/**
 * What gets handed to `drizzle(neon(url), { schema })` and to
 * `drizzleAdapter(db, { provider: 'pg', schema })`.
 *
 * Deliberately NOT `export * from './schema'`: a namespace object is exactly
 * what the adapter expects, and an explicit list means a new table cannot be
 * added to the file without someone noticing it is missing here.
 */
export const schema = {
	user,
	session,
	account,
	verification,
	passkey,
	twoFactor,
	appliedOp,
	list,
	task,

	userRelations,
	sessionRelations,
	accountRelations,
	passkeyRelations,
	twoFactorRelations,
	listRelations,
	taskRelations,
	appliedOpRelations
};

/** The invariant that makes the pull cursor correct. Asserted in tests. */
export const REV_SEQUENCED_TABLES = [list, task] as const;

export type ListRow = typeof list.$inferSelect;
export type TaskRow = typeof task.$inferSelect;
export type AppliedOpRow = typeof appliedOp.$inferSelect;
export type UserRow = typeof user.$inferSelect;
